FROM registry.redhat.io/rhoai/odh-pipeline-runtime-pytorch-cuda-py312-rhel9@sha256:aa457e7394ba73350f5c8e08c56ddba126d9472197e7669c9eb7daa2c02e6777

ENV OMP_NUM_THREADS=4 \
    DOCLING_ARTIFACTS_PATH=/opt/app-root/src/.cache/docling/models \
    HF_HOME=/tmp/ \
    TORCH_HOME=/tmp/ \
    DEVICE=cpu \
    OCR_ENGINE=rapidocr \
    LOG_LEVEL=INFO

ARG MODELS_LIST="layout tableformer rapidocr"

RUN pip install docling[rapidocr]==2.75.0 opencv-python-headless==4.12.0.88 && \
    echo "Downloading models..." && \
    HF_HUB_DOWNLOAD_TIMEOUT="90" && \
    HF_HUB_ETAG_TIMEOUT="90" && \
    docling-tools models download -o "${DOCLING_ARTIFACTS_PATH}" $MODELS_LIST && \
    chown -R 1001:0 ${DOCLING_ARTIFACTS_PATH} && \
    chmod -R g=u ${DOCLING_ARTIFACTS_PATH}

WORKDIR /opt/app-root/src

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src/

ENV PYTHONPATH=/opt/app-root/src/src

EXPOSE 8080

USER 1001

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
