FROM quay.io/bball/docling-rapidocr-pipeline:1.0

WORKDIR /opt/app-root/src

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/func.py .

ENV PORT=8080

EXPOSE 8080

CMD ["python", "func.py"]
