apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: openai-responses-api-secure
spec:
  replicas: 1
  server:
    containerSpec:
      env:
        - name: VLLM_URL
          value: 'https://gemma-4-predictor.sandbox.svc.cluster.local:8443/v1'
        - name: VLLM_TLS_VERIFY
          value: 'false'
        - name: VLLM_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: default-name-gemma-4-sa
        - name: INFERENCE_MODEL
          value: gemma-4
        - name: ENABLE_SENTENCE_TRANSFORMERS
          value: 'true'
        - name: EMBEDDING_PROVIDER
          value: sentence-transformers
        - name: EMBEDDING_MODEL
          value: granite-embedding-125m-english
        - name: EMBEDDING_PROVIDER_MODEL_ID
          value: ibm-granite/granite-embedding-125m-english
        - name: POSTGRES_HOST
          value: lls-postgresql.sandbox.svc.cluster.local
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: database-name
              name: lls-postgresql
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: lls-postgresql
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: lls-postgresql
      name: llama-stack
      port: 8321
      ##### Manage Through SSO ####
      #
      #auth:
      #  provider_config:
      #    type: "oauth2_token"
      #    jwks:
      #      uri: "https://my-keycloak-server.com/realms/llamastack-demo/protocol/openid-connect/certs" 
      #      key_recheck_period: 3600
      #    issuer: "https://my-keycloak-server.com/realms/llamastack-demo" 
      #    audience: "account"
      #    verify_tls: true
      #    claims_mapping:
      #      llamastack_roles: "roles" 
      #  access_policy:
      #    - permit: 
      #        actions: [read]
      #        resource: model::vllm-inference/gemma-4
      #      description: Allow all authenticated users to access Llama 3.2 model
    distribution:
      name: 'rh-dev'
    storage:
      size: 50Gi
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: openai-responses-api-secure
  annotations:
    haproxy.router.openshift.io/timeout: 300s
spec:
  to:
    kind: Service
    name: openai-responses-api-secure-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
