apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.kservice.name }}
spec:
  template:
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.kservice.port }}
          env:
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: docling-azure-storage
                  key: connection-string
