apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.kservice.name }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.kservice.port }}
          env:
            - name: PORT
              value: {{ .Values.kservice.port | quote }}
