apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceServiceConfig
metadata:
  annotations:
    platform.opendatahub.io/instance.name: default-kserve
    openshift.io/description: Red Hat AI Inference v3.5.0 - NVIDIA CUDA GPU LLMInferenceServiceConfig for LLMInferenceService.
    openshift.io/display-name: Red Hat AI Inference v3.5.0 [NVIDIA CUDA GPU]
    serving.kserve.io/well-known-config: 'true'
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
  name: custom-rhaii-3.5.0-kserve-config-llm-template-nvidia-cuda
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/part-of: kserve
    app.opendatahub.io/kserve: 'true'
    opendatahub.io/config-type: accelerator
    platform.opendatahub.io/part-of: kserve
spec:
  template:
    containers:
      - image: 'registry.redhat.io/rhaii/vllm-cuda-rhel9:3.5.0-1786533823'
        name: main
        env:
          - name: HF_HOME
            value: /tmp/hf_home
