apiVersion: v1
kind: Pod
metadata:
  name: docling-as-pod
spec:
  containers:
    - name: docling-test
      image: quay.io/bball/docling-rapidocr-pipeline:1.0
      imagePullPolicy: Always
      command: ['sh', '-c', 'curl https://raw.githubusercontent.com/glroland/mechanic/cf1cd0395b867edacd3f69ac32737763617d1dbd/chatbot/src/assets/c3_repair.pdf > /tmp/input.pdf; docling --from pdf --to md --image-export-mode referenced --ocr-engine rapidocr --ocr --output output.pdf /tmp/input.pdf']
      resources:
        requests:
          memory: "2Gi"
          cpu: "5000m"
          nvidia.com/gpu: "1"
        limits:
          memory: "6Gi"
          cpu: "5000m"
          nvidia.com/gpu: "1"
